### PR TITLE
Update Scyther to support wxPython 4.0

### PR DESCRIPTION
**Pull request by Thomas-Fleming**
Fix wxPython SpashScreen error at startup.
Fix deprecated class usage and function calls.

### CODE REVIEW

**Comment by maerten** [comment]
FYI there's some additional calls that don't work for me
This is the error I get when pressing CMD+S to save the file:

```
$ ./scyther-gui.py
Traceback (most recent call last):
  File "scyther-mac-v1.1.3/Gui/Mainwindow.py", line 281, in OnSave
    return self.OnSaveAs(event)
  File "scyther-mac-v1.1.3/Gui/Mainwindow.py", line 301, in OnSaveAs
    if self.askUserForFilename(defaultFile=self.filename, style=wx.SAVE,
AttributeError: 'module' object has no attribute 'SAVE'
```

**Comment by Thomas-Fleming** [comment]
Thanks, Maerten. I'll take a look when I get a spare minute.

**Comment by cascremers** [comment]
Thanks a lot for the effort, it's really appreciated!
Two suggestions that would help but I can't get round to them myself in the next weeks:
 - Perhaps an explicit check for the allowed versions of wxpython, and
 - a corresponding warning that explains if a condition is not met (and mentions in the install readmes perhaps?).

**Comment by cascremers** [comment]
This issue should have been resolved now in current versions of Scyther's code. Will be closing this issue in the near future unless someone objects.

**Pull request closed without merging**
